language: python
python:
   - "2.7"
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
install:
  - pip install Cython --install-option="--no-cython-compile"
  - travis_wait 30 pip install -r requirements.txt
script:
  - cd flux_balance_analysis/
  - pytest
